### ISSUE TITLE
New Site - Foxhole Planner

### ISSUE THREAD

**Issue by joshuaHallee** [pogobanane/foxhole-list#1]
I found this site that was posted by a user on reddit.

https://foxholeplanner.com/
https://github.com/brandon-ray/foxhole-facility-planner

**Comment by pogoba** [comment]
thanks! f7e83e949aa0549e6d7319fcafc2880573368c1a

**Comment by pogoba** [comment]
this one also exists, but i dont know who did it/where the source is https://bunker.drownedvale.club/
